'use client';
import { ChangeEvent, FormEvent, useCallback, useEffect, useMemo, useState } from 'react';

type Node = { ID: string; State: string; CapacityBytes: number; UsedBytes: number; Failures: number; LastHeartbeat: string };
type Replica = { NodeID: string; State: string; Version: number; SHA256: string; Size: number };
type ObjectDetail = { object: { Key: string; LatestVersion: number; ReplicationFactor: number; State: string }; version: { SHA256: string; Size: number }; replicas: Replica[] };
type Repair = { id: number; key: string; version: number; source: string; target: string; reason: string; state: string; attempts: number; error: string; created_at: string; updated_at: string };
type Event = { id: number; type: string; key: string; version: number; node: string; details: string; at: string };

const api = async <T,>(path: string, init?: RequestInit): Promise<T> => { const r = await fetch(`/api${path}`, { ...init, cache: 'no-store' }); if (!r.ok) throw new Error(await r.text() || r.statusText); return r.json() as Promise<T>; };
const bytes = (value: number): string => value < 1024 ? `${value} B` : `${(value / 1024).toFixed(1)} KiB`;

export default function Dashboard(): React.ReactNode {
  const [nodes, setNodes] = useState<Node[]>([]); const [objects, setObjects] = useState<ObjectDetail[]>([]); const [repairs, setRepairs] = useState<Repair[]>([]); const [events, setEvents] = useState<Event[]>([]);
  const [status, setStatus] = useState('Connecting to coordinator…'); const [error, setError] = useState(''); const [file, setFile] = useState<File | null>(null); const [key, setKey] = useState(''); const [policy, setPolicy] = useState('BALANCED'); const [faultNode, setFaultNode] = useState('n1'); const [faultKey, setFaultKey] = useState(''); const [faultVersion, setFaultVersion] = useState(1);
  const refresh = useCallback(async (): Promise<void> => { try { const [cluster, list, repairRows, eventRows] = await Promise.all([api<Node[]>('/v1/cluster'), api<{ Key: string }[]>('/v1/objects'), api<Repair[]>('/v1/repairs'), api<Event[]>('/v1/events')]); const details = await Promise.all(list.map((o) => api<ObjectDetail>(`/v1/objects/${encodeURIComponent(o.Key)}?metadata=1`))); setNodes(cluster); setObjects(details); setRepairs(repairRows); setEvents(eventRows); setError(''); setStatus(`Updated ${new Date().toLocaleTimeString()}`); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to reach coordinator'); setStatus('Coordinator unavailable'); } }, []);
  useEffect(() => { void refresh(); const id = window.setInterval(() => void refresh(), 3000); return () => window.clearInterval(id); }, [refresh]);
  const upload = useCallback(async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!file || !key.trim()) { setError('Choose a file and provide an object key.'); return; } try { setStatus('Uploading and verifying replicas…'); const body = await file.arrayBuffer(); await api(`/v1/objects/${encodeURIComponent(key)}?policy=${policy}`, { method: 'PUT', body }); setStatus('Upload committed.'); setFile(null); setKey(''); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Upload failed'); } }, [file, key, policy, refresh]);
  const admin = useCallback(async (action: string): Promise<void> => { try { setStatus(`Running ${action}…`); await api(`/v1/admin/${action}`, { method: 'POST' }); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Operation failed'); } }, [refresh]);
  const nodeAction = useCallback(async (action: 'partition' | 'corrupt', payload: Record<string, unknown>): Promise<void> => { try { setStatus(`Running ${action} on ${faultNode}…`); await api(`/v1/admin/nodes/${faultNode}/${action}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Node action failed'); } }, [faultNode, refresh]);
  const download = useCallback(async (objectKey: string): Promise<void> => { const response = await fetch(`/api/v1/objects/${encodeURIComponent(objectKey)}`); if (!response.ok) { setError(await response.text()); return; } const url = URL.createObjectURL(await response.blob()); const anchor = document.createElement('a'); anchor.href = url; anchor.download = objectKey; anchor.click(); URL.revokeObjectURL(url); }, []);
  const summary = useMemo(() => ({ online: nodes.filter((n) => n.State === 'ONLINE').length, degraded: nodes.filter((n) => n.State !== 'ONLINE').length, healthy: objects.filter((o) => o.object.State === 'HEALTHY').length }), [nodes, objects]);
  return <main><header><p className="eyebrow">FORGER / DISTRIBUTED OBJECT STORAGE</p><h1>Cluster control plane</h1><p>Live coordinator state, verified replica placement, and safe repair controls.</p><p role="status" className="status">{status}</p>{error && <p role="alert" className="error">{error}</p>}</header>
    <section className="metrics" aria-label="Cluster summary"><article><b>{summary.online}/{nodes.length}</b><span>nodes online</span></article><article><b>{summary.healthy}/{objects.length}</b><span>healthy objects</span></article><article><b>{repairs.filter((r) => r.state === 'RUNNING' || r.state === 'QUEUED').length}</b><span>active repairs</span></article></section>
    <section className="panel"><h2>Upload object</h2><form onSubmit={upload}><label>Object key<input value={key} onChange={(e) => setKey(e.target.value)} required placeholder="demo/video.bin" /></label><label>Durability policy<select value={policy} onChange={(e) => setPolicy(e.target.value)}><option>FAST</option><option>BALANCED</option><option>DURABLE</option></select></label><label>File<input type="file" required onChange={(e: ChangeEvent<HTMLInputElement>) => setFile(e.target.files?.[0] ?? null)} /></label><button type="submit">Upload and replicate</button></form></section>
    <section className="panel"><h2>Demo controls</h2><div className="controls"><button onClick={() => void admin('scan')}>Run integrity scan</button><button onClick={() => void admin('repair')}>Queue repairs</button><button onClick={() => void admin('reconcile')}>Reconcile metadata</button><button onClick={() => void admin('rebalance')}>Rebalance safely</button><button onClick={() => void refresh()}>Refresh now</button></div><form className="fault-form" onSubmit={(e) => { e.preventDefault(); void nodeAction('corrupt', { key: faultKey, version: faultVersion }); }}><label>Node<select value={faultNode} onChange={(e) => setFaultNode(e.target.value)}>{nodes.map((n) => <option key={n.ID}>{n.ID}</option>)}</select></label><label>Object key<input value={faultKey} onChange={(e) => setFaultKey(e.target.value)} required /></label><label>Version<input type="number" min="1" value={faultVersion} onChange={(e) => setFaultVersion(Number(e.target.value))} required /></label><button type="submit">Corrupt selected replica</button><button type="button" onClick={() => void nodeAction('partition', { enabled: true })}>Partition node</button><button type="button" onClick={() => void nodeAction('partition', { enabled: false })}>Restore node</button></form><p className="hint">These protected controls call the coordinator; no node URL or token is exposed to the browser.</p></section>
    <section className="panel"><h2>Nodes</h2><div className="cards">{nodes.map((n) => <article className="node" key={n.ID}><h3>{n.ID} <span className={`badge ${n.State.toLowerCase()}`}>{n.State}</span></h3><dl><dt>Utilization</dt><dd>{bytes(n.UsedBytes)} / {bytes(n.CapacityBytes)}</dd><dt>Heartbeat failures</dt><dd>{n.Failures}</dd><dt>Last heartbeat</dt><dd>{new Date(n.LastHeartbeat).toLocaleTimeString()}</dd></dl></article>)}</div></section>
    <section className="panel"><h2>Objects and replica placement</h2><div className="object-list">{objects.map((o) => <article className="object" key={o.object.Key}><div><h3>{o.object.Key}</h3><p>v{o.object.LatestVersion} · RF {o.object.ReplicationFactor} · <strong>{o.replicas.filter((r) => r.State === 'HEALTHY').length}/{o.object.ReplicationFactor} healthy</strong></p><p className="mono">SHA-256 {o.version.SHA256}</p></div><button onClick={() => void download(o.object.Key)}>Download</button><table><caption className="sr-only">Replica locations for {o.object.Key}</caption><thead><tr><th>Node</th><th>State</th><th>Version</th><th>Checksum</th></tr></thead><tbody>{o.replicas.map((r) => <tr key={r.NodeID}><td>{r.NodeID}</td><td><span className={`badge ${r.State.toLowerCase()}`}>{r.State}</span></td><td>v{r.Version}</td><td className="mono">{r.SHA256.slice(0, 16)}…</td></tr>)}</tbody></table></article>)}</div></section>
    <section className="panel"><h2>Repair jobs</h2><table><thead><tr><th>Object</th><th>Version</th><th>Source → Target</th><th>Reason</th><th>State</th><th>Attempts</th><th>Updated</th></tr></thead><tbody>{repairs.map((r) => <tr key={r.id}><td>{r.key}</td><td>v{r.version}</td><td>{r.source || 'selecting'} → {r.target}</td><td>{r.reason}</td><td><span className={`badge ${r.state.toLowerCase()}`}>{r.state}</span></td><td>{r.attempts}</td><td>{new Date(r.updated_at).toLocaleTimeString()}</td></tr>)}</tbody></table></section>
    <section className="panel"><h2>Event timeline</h2><ol className="events">{events.map((event) => <li key={event.id}><strong>{event.type}</strong><span>{event.key && `${event.key} v${event.version} · `}{event.node} · {new Date(event.at).toLocaleTimeString()}</span><code>{event.details}</code></li>)}</ol></section>
  </main>;
}
